### ISSUE TITLE
Can not generate two tokens

### ISSUE THREAD

**Issue by tmcpro** [signnow/SignNowNodeSDK#1]
We were integrating the API into our site we are launching in 3 weeks and during development/testing we are not able to upload two documents using the node package with different tokens. The first one uploads fine, then when we go to upload the second document we try to generate a second token and get a timeout error.

I have uploaded a sample script that demonstrates the second token hanging and then timing out with no response back from the endpoint. 

https://github.com/tmcpro/signnow-issue

cc: @diego-pacheco

**Comment by diego-pacheco** [comment]
+1

**Comment by mfitchett** [comment]
The issue was do to an incorrect Content-Length being set in the header of the document create request. The request would stay open even after returning the callback preventing other request from being made.

**Comment by tmcpro** [comment]
Thanks!

**Comment by mfitchett** [comment]
I'm reopening the issue, the fix broke support for larger files. I had to revert back to supplying a Content-Length in the header which breaks support for chained request. I will be submitting a ticket to Node.

**Comment by dannymcpherson** [comment]
Is anyone still maintaining this SDK?  I'm having similar errors where the first request or two works fine, but then the next one hangs.

**Comment by dannymcpherson** [comment]
I added some console logging to gather more info for the failures.

Scenario 1:
1. Call oauth2.requestToken - successfully returns access_token
2. Call oauth2.verify (with received token) - fails with the following response, which fails to be parsed by JSON:

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator,
 root@localhost and inform them of the time the error occurred,
and anything you might have done that may have
caused the error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache Server at api.signnow.com Port 443</address>
</body></html>
```

Scenario 2:
1. Call oauth2.requestToken - successfully returns access_token
2. Call document.create - successfully uploads/creates document
3. Call document.update - fails with the following response:
```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator,
 root@localhost and inform them of the time the error occurred,
and anything you might have done that may have
caused the error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache Server at api.signnow.com Port 443</address>
</body></html>
```

Help would be greatly appreciated.

**Comment by dannymcpherson** [comment]
I was able to get around this issue by setting the Content-Length to 0 anytime there is no body sent in the request:
```javascript
common.options.headers['Content-Length'] = 0;
```

This is a problem with many different API calls within the SDK.

**Comment by russellswift** [comment]
New version of package has been released today. New name is `@signnow/api-client`. Please, check if problem has gone
