### ISSUE TITLE
Error uploading pdf files

### ISSUE THREAD

**Issue by diego-pacheco** [signnow/SignNowNodeSDK#2]
Related to https://github.com/signnow/SignNowNodeSDK/issues/1

When trying to upload a pdf (right now it seems like any pdf with more than one page will fail), I receive this error message in the response body: *{ errors: [ { code: 65536, message: 'Must upload one file' } ] }*

I have uploaded an example providing 2 pdf files, one that fails, and one that succeeds.

See reproducible error here: https://github.com/diego-pacheco/signnow-issue

cc: @tmcpro

**Comment by mfitchett** [comment]
The change I made for #1 broke the upload for large files. The way I originally had it was correct. The issue appears to be with Node.js. I have read through all of the documentation on streams and http request and tried different solutions posted on Stackoverflow by people with similar problems. 

I posted a question (http://stackoverflow.com/questions/29222475/node-js-pipe-file-to-multipart-form-data-https-request-causes-next-request-to-ti) on Stackoverflow to see if anyone else might have any ideas. I will give it a couple days then submit a bug to Node.

**Comment by tmcpro** [comment]
@mfitchett we are going to roll back to the old version and keep the token in redis for now until we find a fix. Thanks

cc @diego-pacheco

**Comment by benWillan** [comment]
> Related to #1
> 
> When trying to upload a pdf (right now it seems like any pdf with more than one page will fail), I receive this error message in the response body: _{ errors: [ { code: 65536, message: 'Must upload one file' } ] }_
> 
> I have uploaded an example providing 2 pdf files, one that fails, and one that succeeds.
> 
> See reproducible error here: https://github.com/diego-pacheco/signnow-issue
> 
> cc: @tmcpro

Old post but I'm using SignNow API to upload a .pdf and receive the same error message. How did you resolve this please @diego-pacheco? I've tried using a single-page test pdf file in a simple format (export from MS word) with no input fields. I've tried referring to the file using both relative and absolute paths. My Post request is sent to:
https://api-eval.signnow.com/document endpoint and I have a method that retrieves my Bearer token prior to my Post request being submitted.

**Comment by lubosdz** [comment]
Same here - using PHP SDK - same error. Tried guzzle client and multipart client - same errors. First error is `Using self-signed certificate in chain`, then once disabled peer verification response code `400` - `Client error: POST https://api-eval.signnow.com/document` resulted in a `400 Bad Request response: {"errors":[{"code":65579,"message":"Must upload one file"}]} ]`. Whatever I try, still same. But when I inject some simple short string `abcxyz` - it will be shown in API logs dashboard. Checked also some other clients - cURL, PHP's file_get_contents via stream_context .. Looks like uploading standard PDF file not possible :-( API documentation also lacks return codes 400 for `/document`.
